# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
    # Trigger the workflow on pushes to the main (or master) branch
    push:
        branches:
            - main # IMPORTANT: Change this to 'master' if your primary branch is named master
            # If you have a different branch for development that you want to deploy from, specify it here.

    # Allow the workflow to be run manually from the Actions tab
    workflow_dispatch:

# Grant GITHUB_TOKEN the necessary permissions for deployment
permissions:
    contents: read # To checkout the repository code
    pages: write # To deploy to GitHub Pages
    id-token: write # Required for OIDC authentication by deploy-pages

# Ensure only one deployment is running at a time
concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    # Build job to create the production artifacts
    build:
        runs-on: ubuntu-latest # Use the latest Ubuntu runner
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4 # Action to checkout your code

            - name: Set up Node.js
              uses: actions/setup-node@v4 # Action to set up Node.js environment
              with:
                  node-version: "20" # Specify your desired Node.js version (e.g., '18', '20', '22')
                  cache: "npm" # Cache npm dependencies for faster builds

            - name: Install dependencies
              run: npm install # Run npm install to get all project dependencies

            - name: Build project
              run: npm run build # Run your project's build script (creates the 'dist' folder)

            - name: Upload production artifact
              uses: actions/upload-pages-artifact@v3 # Action to upload the 'dist' folder
              with:
                  path: "./dist" # The path to your built files

    # Deploy job to publish the artifacts to GitHub Pages
    deploy:
        environment:
            name: github-pages # Use the 'github-pages' environment
            url: ${{ steps.deployment.outputs.page_url }} # The URL where the site will be deployed
        runs-on: ubuntu-latest
        needs: build # This job depends on the 'build' job completing successfully
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4 # Official action to deploy to GitHub Pages
